
include(GNUInstallDirs)

if(WITH_PORTABLE OR WIN32)
    # flatten everything
    set(CMAKE_INSTALL_BINDIR "${CMAKE_INSTALL_PREFIX}")
    set(CMAKE_INSTALL_LIBDIR "${CMAKE_INSTALL_PREFIX}")
    set(CMAKE_INSTALL_DATADIR "${CMAKE_INSTALL_PREFIX}")
    set(SQLITESTUDIO_INSTALL_DATADIR "${CMAKE_INSTALL_DATADIR}")
    set(SQLITESTUDIO_INSTALL_PLUGINDIR "${CMAKE_INSTALL_LIBDIR}/plugins")
else()
    set(SQLITESTUDIO_INSTALL_DATADIR "${CMAKE_INSTALL_DATADIR}/sqlitestudio")
    set(SQLITESTUDIO_INSTALL_PLUGINDIR "${CMAKE_INSTALL_LIBDIR}/sqlitestudio")
endif()

set(SQLITESTUDIO_INSTALL_STYLEDIR "${SQLITESTUDIO_INSTALL_PLUGINDIR}/styles")
