set(DIR_OF_VERSION_CMAKE ${CMAKE_CURRENT_LIST_DIR})

function(sqlitestudio_find_version)
    set(SQLITESTUDIO_CPP_PATH "${DIR_OF_VERSION_CMAKE}/../coreSQLiteStudio/sqlitestudio.cpp")

    file(STRINGS "${SQLITESTUDIO_CPP_PATH}" SQLITESTUDIO_VERSION_LINE REGEX "sqlitestudioVersion *= *([0-9]+)")
    if(NOT SQLITESTUDIO_VERSION_LINE)
        message(FATAL_ERROR "Could not find 'sqlitestudioVersion' in ${SQLITESTUDIO_CPP_PATH}")
    endif()

    if(SQLITESTUDIO_VERSION_LINE MATCHES "sqlitestudioVersion *= *([0-9]+)")
        set(SQLITESTUDIO_VERSION_INT "${CMAKE_MATCH_1}")
    else()
        message(FATAL_ERROR "Could not extract version number from '${SQLITESTUDIO_VERSION_LINE}'")
    endif()

    math(EXPR SQLITESTUDIO_VERSION_MAJOR "${SQLITESTUDIO_VERSION_INT} / 10000")
    math(EXPR SQLITESTUDIO_VERSION_MINOR "(${SQLITESTUDIO_VERSION_INT} / 100) % 100")
    math(EXPR SQLITESTUDIO_VERSION_PATCH "${SQLITESTUDIO_VERSION_INT} % 100")

    set(SQLITESTUDIO_VERSION_STRING "${SQLITESTUDIO_VERSION_MAJOR}.${SQLITESTUDIO_VERSION_MINOR}.${SQLITESTUDIO_VERSION_PATCH}")

    message(STATUS "SQLiteStudio version: ${SQLITESTUDIO_VERSION_STRING} (${SQLITESTUDIO_VERSION_INT})")

    set(SQLITESTUDIO_VERSION_INT "${SQLITESTUDIO_VERSION_INT}" PARENT_SCOPE)
    set(SQLITESTUDIO_VERSION_MAJOR "${SQLITESTUDIO_VERSION_MAJOR}" PARENT_SCOPE)
    set(SQLITESTUDIO_VERSION_MINOR "${SQLITESTUDIO_VERSION_MINOR}" PARENT_SCOPE)
    set(SQLITESTUDIO_VERSION_PATCH "${SQLITESTUDIO_VERSION_PATCH}" PARENT_SCOPE)
    set(SQLITESTUDIO_VERSION_STRING "${SQLITESTUDIO_VERSION_STRING}" PARENT_SCOPE)
endfunction()
