#define TK3_ILLEGAL                          1
#define TK3_COMMENT                          2
#define TK3_SPACE                            3
#define TK3_ID                               4
#define TK3_ABORT                            5
#define TK3_ACTION                           6
#define TK3_AFTER                            7
#define TK3_ANALYZE                          8
#define TK3_ASC                              9
#define TK3_ATTACH                          10
#define TK3_BEFORE                          11
#define TK3_BEGIN                           12
#define TK3_BY                              13
#define TK3_CASCADE                         14
#define TK3_CAST                            15
#define TK3_COLUMNKW                        16
#define TK3_CONFLICT                        17
#define TK3_DATABASE                        18
#define TK3_DEFERRED                        19
#define TK3_DESC                            20
#define TK3_DETACH                          21
#define TK3_EACH                            22
#define TK3_END                             23
#define TK3_EXCLUSIVE                       24
#define TK3_EXPLAIN                         25
#define TK3_FAIL                            26
#define TK3_FOR                             27
#define TK3_IGNORE                          28
#define TK3_IMMEDIATE                       29
#define TK3_INDEXED                         30
#define TK3_INITIALLY                       31
#define TK3_INSTEAD                         32
#define TK3_LIKE_KW                         33
#define TK3_MATCH                           34
#define TK3_NO                              35
#define TK3_PLAN                            36
#define TK3_QUERY                           37
#define TK3_KEY                             38
#define TK3_OF                              39
#define TK3_OFFSET                          40
#define TK3_PRAGMA                          41
#define TK3_RAISE                           42
#define TK3_RELEASE                         43
#define TK3_REPLACE                         44
#define TK3_RESTRICT                        45
#define TK3_ROW                             46
#define TK3_ROLLBACK                        47
#define TK3_SAVEPOINT                       48
#define TK3_TEMP                            49
#define TK3_TRIGGER                         50
#define TK3_VACUUM                          51
#define TK3_VIEW                            52
#define TK3_VIRTUAL                         53
#define TK3_WITHOUT                         54
#define TK3_REINDEX                         55
#define TK3_RENAME                          56
#define TK3_CTIME_KW                        57
#define TK3_IF                              58
#define TK3_ANY                             59
#define TK3_OR                              60
#define TK3_AND                             61
#define TK3_NOT                             62
#define TK3_IS                              63
#define TK3_BETWEEN                         64
#define TK3_IN                              65
#define TK3_ISNULL                          66
#define TK3_NOTNULL                         67
#define TK3_NE                              68
#define TK3_EQ                              69
#define TK3_GT                              70
#define TK3_LE                              71
#define TK3_LT                              72
#define TK3_GE                              73
#define TK3_ESCAPE                          74
#define TK3_BITAND                          75
#define TK3_BITOR                           76
#define TK3_LSHIFT                          77
#define TK3_RSHIFT                          78
#define TK3_PLUS                            79
#define TK3_MINUS                           80
#define TK3_STAR                            81
#define TK3_SLASH                           82
#define TK3_REM                             83
#define TK3_CONCAT                          84
#define TK3_COLLATE                         85
#define TK3_BITNOT                          86
#define TK3_SEMI                            87
#define TK3_TRANSACTION                     88
#define TK3_ID_TRANS                        89
#define TK3_COMMIT                          90
#define TK3_TO                              91
#define TK3_CREATE                          92
#define TK3_TABLE                           93
#define TK3_LP                              94
#define TK3_RP                              95
#define TK3_AS                              96
#define TK3_DOT                             97
#define TK3_ID_TAB_NEW                      98
#define TK3_ID_DB                           99
#define TK3_CTX_ROWID_KW                   100
#define TK3_EXISTS                         101
#define TK3_COMMA                          102
#define TK3_ID_COL_NEW                     103
#define TK3_STRING                         104
#define TK3_JOIN_KW                        105
#define TK3_ID_COL_TYPE                    106
#define TK3_CONSTRAINT                     107
#define TK3_DEFAULT                        108
#define TK3_NULL                           109
#define TK3_PRIMARY                        110
#define TK3_UNIQUE                         111
#define TK3_CHECK                          112
#define TK3_REFERENCES                     113
#define TK3_ID_CONSTR                      114
#define TK3_ID_COLLATE                     115
#define TK3_ID_TAB                         116
#define TK3_INTEGER                        117
#define TK3_FLOAT                          118
#define TK3_BLOB                           119
#define TK3_AUTOINCR                       120
#define TK3_ON                             121
#define TK3_INSERT                         122
#define TK3_DELETE                         123
#define TK3_UPDATE                         124
#define TK3_ID_FK_MATCH                    125
#define TK3_SET                            126
#define TK3_DEFERRABLE                     127
#define TK3_FOREIGN                        128
#define TK3_DROP                           129
#define TK3_ID_VIEW_NEW                    130
#define TK3_ID_VIEW                        131
#define TK3_UNION                          132
#define TK3_ALL                            133
#define TK3_EXCEPT                         134
#define TK3_INTERSECT                      135
#define TK3_SELECT                         136
#define TK3_DISTINCT                       137
#define TK3_ID_ALIAS                       138
#define TK3_FROM                           139
#define TK3_USING                          140
#define TK3_JOIN                           141
#define TK3_ID_JOIN_OPTS                   142
#define TK3_ID_IDX                         143
#define TK3_ORDER                          144
#define TK3_GROUP                          145
#define TK3_HAVING                         146
#define TK3_LIMIT                          147
#define TK3_WHERE                          148
#define TK3_ID_COL                         149
#define TK3_INTO                           150
#define TK3_VALUES                         151
#define TK3_VARIABLE                       152
#define TK3_CASE                           153
#define TK3_ID_FN                          154
#define TK3_ID_ERR_MSG                     155
#define TK3_WHEN                           156
#define TK3_THEN                           157
#define TK3_ELSE                           158
#define TK3_INDEX                          159
#define TK3_ID_IDX_NEW                     160
#define TK3_ID_PRAGMA                      161
#define TK3_ID_TRIG_NEW                    162
#define TK3_ID_TRIG                        163
#define TK3_ALTER                          164
#define TK3_ADD                            165
