#ifndef DBSQLITESYSTEMDATA_GLOBAL_H
#define DBSQLITESYSTEMDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DBSQLITESYSTEMDATA_LIBRARY)
#  define DBSQLITESYSTEMDATASHARED_EXPORT Q_DECL_EXPORT
#else
#  define DBSQLITESYSTEMDATASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DBSQLITESYSTEMDATA_GLOBAL_H
