#ifndef DBFEXPORT_GLOBAL_H
#define DBFEXPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DBFEXPORT_LIBRARY)
#  define DBFEXPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DBFEXPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DBFEXPORT_GLOBAL_H
