#define TK2_ILLEGAL                          1
#define TK2_COMMENT                          2
#define TK2_SPACE                            3
#define TK2_ID                               4
#define TK2_ABORT                            5
#define TK2_AFTER                            6
#define TK2_ASC                              7
#define TK2_ATTACH                           8
#define TK2_BEFORE                           9
#define TK2_BEGIN                           10
#define TK2_CASCADE                         11
#define TK2_CLUSTER                         12
#define TK2_CONFLICT                        13
#define TK2_COPY                            14
#define TK2_DATABASE                        15
#define TK2_DEFERRED                        16
#define TK2_DELIMITERS                      17
#define TK2_DESC                            18
#define TK2_DETACH                          19
#define TK2_EACH                            20
#define TK2_END                             21
#define TK2_EXPLAIN                         22
#define TK2_FAIL                            23
#define TK2_FOR                             24
#define TK2_GLOB                            25
#define TK2_IGNORE                          26
#define TK2_IMMEDIATE                       27
#define TK2_INITIALLY                       28
#define TK2_INSTEAD                         29
#define TK2_LIKE                            30
#define TK2_MATCH                           31
#define TK2_KEY                             32
#define TK2_OF                              33
#define TK2_OFFSET                          34
#define TK2_PRAGMA                          35
#define TK2_RAISE                           36
#define TK2_REPLACE                         37
#define TK2_RESTRICT                        38
#define TK2_ROW                             39
#define TK2_STATEMENT                       40
#define TK2_TEMP                            41
#define TK2_TRIGGER                         42
#define TK2_VACUUM                          43
#define TK2_VIEW                            44
#define TK2_OR                              45
#define TK2_AND                             46
#define TK2_NOT                             47
#define TK2_EQ                              48
#define TK2_NE                              49
#define TK2_ISNULL                          50
#define TK2_NOTNULL                         51
#define TK2_IS                              52
#define TK2_BETWEEN                         53
#define TK2_IN                              54
#define TK2_GT                              55
#define TK2_GE                              56
#define TK2_LT                              57
#define TK2_LE                              58
#define TK2_BITAND                          59
#define TK2_BITOR                           60
#define TK2_LSHIFT                          61
#define TK2_RSHIFT                          62
#define TK2_PLUS                            63
#define TK2_MINUS                           64
#define TK2_STAR                            65
#define TK2_SLASH                           66
#define TK2_REM                             67
#define TK2_CONCAT                          68
#define TK2_UMINUS                          69
#define TK2_UPLUS                           70
#define TK2_BITNOT                          71
#define TK2_SEMI                            72
#define TK2_TRANSACTION                     73
#define TK2_ID_TRANS                        74
#define TK2_COMMIT                          75
#define TK2_ROLLBACK                        76
#define TK2_CREATE                          77
#define TK2_TABLE                           78
#define TK2_LP                              79
#define TK2_RP                              80
#define TK2_AS                              81
#define TK2_DOT                             82
#define TK2_ID_TAB_NEW                      83
#define TK2_ID_DB                           84
#define TK2_COMMA                           85
#define TK2_ID_COL_NEW                      86
#define TK2_STRING                          87
#define TK2_JOIN_KW                         88
#define TK2_ID_COL_TYPE                     89
#define TK2_DEFAULT                         90
#define TK2_INTEGER                         91
#define TK2_FLOAT                           92
#define TK2_NULL                            93
#define TK2_CONSTRAINT                      94
#define TK2_PRIMARY                         95
#define TK2_UNIQUE                          96
#define TK2_CHECK                           97
#define TK2_REFERENCES                      98
#define TK2_COLLATE                         99
#define TK2_ON                             100
#define TK2_INSERT                         101
#define TK2_DELETE                         102
#define TK2_UPDATE                         103
#define TK2_ID_FK_MATCH                    104
#define TK2_SET                            105
#define TK2_DEFERRABLE                     106
#define TK2_FOREIGN                        107
#define TK2_ID_CONSTR                      108
#define TK2_ID_TAB                         109
#define TK2_DROP                           110
#define TK2_ID_VIEW_NEW                    111
#define TK2_ID_VIEW                        112
#define TK2_UNION                          113
#define TK2_ALL                            114
#define TK2_EXCEPT                         115
#define TK2_INTERSECT                      116
#define TK2_SELECT                         117
#define TK2_DISTINCT                       118
#define TK2_ID_ALIAS                       119
#define TK2_FROM                           120
#define TK2_USING                          121
#define TK2_JOIN                           122
#define TK2_ID_JOIN_OPTS                   123
#define TK2_ORDER                          124
#define TK2_BY                             125
#define TK2_GROUP                          126
#define TK2_HAVING                         127
#define TK2_LIMIT                          128
#define TK2_WHERE                          129
#define TK2_ID_COL                         130
#define TK2_INTO                           131
#define TK2_VALUES                         132
#define TK2_VARIABLE                       133
#define TK2_LIKE_KW                        134
#define TK2_CASE                           135
#define TK2_ID_FN                          136
#define TK2_ID_ERR_MSG                     137
#define TK2_WHEN                           138
#define TK2_THEN                           139
#define TK2_ELSE                           140
#define TK2_INDEX                          141
#define TK2_ID_IDX_NEW                     142
#define TK2_ID_IDX                         143
#define TK2_ID_PRAGMA                      144
#define TK2_ID_TRIG_NEW                    145
#define TK2_ID_TRIG                        146
