#ifndef DBASEFORMAT_GLOBAL_H
#define DBASEFORMAT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DBASEFORMAT_LIBRARY)
#  define DBASEFORMATSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DBASEFORMATSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DBASEFORMAT_GLOBAL_H
