<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
  <context>
    <name>HtmlExport</name>
    <message>
      <location filename="../htmlexport.cpp" line="45"/>
      <source>SQL query results</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="77"/>
      <location filename="../htmlexport.cpp" line="154"/>
      <source>no type</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="114"/>
      <location filename="../htmlexport.cpp" line="242"/>
      <source>Exported table: %1</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="126"/>
      <location filename="../htmlexport.cpp" line="254"/>
      <source>Table: %1</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="254"/>
      <source>virtual</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="307"/>
      <source>Exported database: %1</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="323"/>
      <source>Index: %1</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="329"/>
      <source>For table:</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="336"/>
      <source>Unique:</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="337"/>
      <source>Yes</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="337"/>
      <source>No</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="343"/>
      <source>Column</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="344"/>
      <source>Collating</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="345"/>
      <source>Sort order</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="379"/>
      <source>Trigger: %1</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="385"/>
      <source>Activated:</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="393"/>
      <source>Action:</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="400"/>
      <source>On view:</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="402"/>
      <source>On table:</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="413"/>
      <source>Activate condition:</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="420"/>
      <source>Code executed:</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="454"/>
      <source>View: %1</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="479"/>
      <source>Document generated by SQLiteStudio v%1 on %2</source>
      <translation type="unfinished"/>
    </message>
  </context>
  <context>
    <name>HtmlExportConfig</name>
    <message>
      <location filename="../htmlexport.ui" line="36"/>
      <source>Maximum number of characters per cell:</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="43"/>
      <source>Include data types in first row</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="53"/>
      <source>Column names as first row</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="63"/>
      <source>Row numbers as first column</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="73"/>
      <source>Output format</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="79"/>
      <source>Format document (new lines, indentation)</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="92"/>
      <source>Compress (everything in one line)</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="108"/>
      <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
      <translation type="unfinished"/>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="111"/>
      <source>Don&apos;t escape HTML characters</source>
      <translation type="unfinished"/>
    </message>
  </context>
</TS>
