<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="tr" sourcelanguage="en">
<context>
    <name>HtmlExport</name>
    <message>
        <location filename="../htmlexport.cpp" line="45"/>
        <source>SQL query results</source>
        <translation>SQL sorgu sonucu</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="54"/>
        <source>Query:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="94"/>
        <location filename="../htmlexport.cpp" line="188"/>
        <source>no type</source>
        <translation>tip yok</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="125"/>
        <source>Exported table: %1</source>
        <translation>Çıkartılan tablo: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="136"/>
        <source>Exported view: %1</source>
        <translation type="unfinished">Exported view: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="157"/>
        <location filename="../htmlexport.cpp" line="280"/>
        <source>Table: %1</source>
        <translation>Tablo: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="283"/>
        <source>virtual</source>
        <translation>sanal</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="335"/>
        <source>Exported database: %1</source>
        <translation>Çıkartılan veritabanı: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="351"/>
        <source>Index: %1</source>
        <translation>Indeks: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="357"/>
        <source>For table:</source>
        <translation>Hedef tablo:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="364"/>
        <source>Unique:</source>
        <translation>Unique:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>Yes</source>
        <translation>Evet</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>No</source>
        <translation>Hayır</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="371"/>
        <source>Column</source>
        <translation>Kolon</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="372"/>
        <source>Collating</source>
        <translation>Collating</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="373"/>
        <source>Sort order</source>
        <translation>Sıralama düzeni</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="407"/>
        <source>Trigger: %1</source>
        <translation>Trigger: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="413"/>
        <source>Activated:</source>
        <translation>Etkinleştirildi:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="421"/>
        <source>Action:</source>
        <translation>Eylem:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="428"/>
        <source>On view:</source>
        <translation>View:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="430"/>
        <source>On table:</source>
        <translation>Tablo:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="441"/>
        <source>Activate condition:</source>
        <translation>Aktifleştirme koşulu:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="448"/>
        <source>Code executed:</source>
        <translation>Çalıştırılan kod:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="486"/>
        <source>View: %1</source>
        <translation>View: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="563"/>
        <source>Document generated by SQLiteStudio v%1 on %2</source>
        <translation>SQLiteStudio ile üretilen döküman %2 üzerinde v%1</translation>
    </message>
</context>
<context>
    <name>HtmlExportConfig</name>
    <message>
        <location filename="../htmlexport.ui" line="36"/>
        <source>Maximum number of characters per cell:</source>
        <translation>Hücre başına maksimum karakter sayısı:</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="43"/>
        <source>Include data types in first row</source>
        <translation>İlk satırda veri tiplerini içer</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="53"/>
        <source>Column names as first row</source>
        <translation>İlk satıda kolon isimleri</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="63"/>
        <source>Row numbers as first column</source>
        <translation>İlk kolon satır sayıları</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="73"/>
        <source>Output format</source>
        <translation>Çıktı formatı</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="79"/>
        <source>Format document (new lines, indentation)</source>
        <translation>Döküman biçimi (yeni satırlar, girintiler)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="92"/>
        <source>Compress (everything in one line)</source>
        <translation>Sıkıştır (her şeyi bir satırda)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="108"/>
        <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Aktif olduğunda, &amp;lt;, &amp;gt; ve &amp; gibi HTML karakterleri çıkartılan dosyalarda kaçış karakteri olarak değerlendirilmez. Bu size hyper-link içeren dökümanları çıkarmayı sağlar, fakat düzgün olmayan HTLM dökümanına da sebep olabilir (eşleşmeyen &amp;lt; ve &amp;gt; karakterleri gibi). Dikkat edin.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="111"/>
        <source>Don&apos;t escape HTML characters</source>
        <translation>HTML karakterlerini ayırma</translation>
    </message>
</context>
</TS>
