<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="sr" sourcelanguage="en">
  <context>
    <name>HtmlExport</name>
    <message>
      <location filename="../htmlexport.cpp" line="45"/>
      <source>SQL query results</source>
      <translation type="unfinished">SQL query results</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="77"/>
      <location filename="../htmlexport.cpp" line="171"/>
      <source>no type</source>
      <translation type="unfinished">no type</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="108"/>
      <source>Exported table: %1</source>
      <translation type="unfinished">Exported table: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="119"/>
      <source>Exported view: %1</source>
      <translation type="unfinished">Exported view: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="140"/>
      <location filename="../htmlexport.cpp" line="263"/>
      <source>Table: %1</source>
      <translation type="unfinished">Table: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="266"/>
      <source>virtual</source>
      <translation type="unfinished">virtual</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="318"/>
      <source>Exported database: %1</source>
      <translation type="unfinished">Exported database: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="334"/>
      <source>Index: %1</source>
      <translation type="unfinished">Index: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="340"/>
      <source>For table:</source>
      <translation type="unfinished">For table:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="347"/>
      <source>Unique:</source>
      <translation type="unfinished">Unique:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="348"/>
      <source>Yes</source>
      <translation type="unfinished">Yes</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="348"/>
      <source>No</source>
      <translation type="unfinished">No</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="354"/>
      <source>Column</source>
      <translation type="unfinished">Column</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="355"/>
      <source>Collating</source>
      <translation type="unfinished">Collating</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="356"/>
      <source>Sort order</source>
      <translation type="unfinished">Sort order</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="390"/>
      <source>Trigger: %1</source>
      <translation type="unfinished">Trigger: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="396"/>
      <source>Activated:</source>
      <translation type="unfinished">Activated:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="404"/>
      <source>Action:</source>
      <translation type="unfinished">Action:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="411"/>
      <source>On view:</source>
      <translation type="unfinished">On view:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="413"/>
      <source>On table:</source>
      <translation type="unfinished">On table:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="424"/>
      <source>Activate condition:</source>
      <translation type="unfinished">Activate condition:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="431"/>
      <source>Code executed:</source>
      <translation type="unfinished">Code executed:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="469"/>
      <source>View: %1</source>
      <translation type="unfinished">View: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="546"/>
      <source>Document generated by SQLiteStudio v%1 on %2</source>
      <translation type="unfinished">Document generated by SQLiteStudio v%1 on %2</translation>
    </message>
  </context>
  <context>
    <name>HtmlExportConfig</name>
    <message>
      <location filename="../htmlexport.ui" line="36"/>
      <source>Maximum number of characters per cell:</source>
      <translation type="unfinished">Maximum number of characters per cell:</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="43"/>
      <source>Include data types in first row</source>
      <translation type="unfinished">Include data types in first row</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="53"/>
      <source>Column names as first row</source>
      <translation type="unfinished">Column names as first row</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="63"/>
      <source>Row numbers as first column</source>
      <translation type="unfinished">Row numbers as first column</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="73"/>
      <source>Output format</source>
      <translation type="unfinished">Output format</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="79"/>
      <source>Format document (new lines, indentation)</source>
      <translation type="unfinished">Format document (new lines, indentation)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="92"/>
      <source>Compress (everything in one line)</source>
      <translation type="unfinished">Compress (everything in one line)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="108"/>
      <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
      <translation>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="111"/>
      <source>Don&apos;t escape HTML characters</source>
      <translation type="unfinished">Don&apos;t escape HTML characters</translation>
    </message>
  </context>
</TS>
