<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="es-ES" sourcelanguage="en">
<context>
    <name>HtmlExport</name>
    <message>
        <location filename="../htmlexport.cpp" line="45"/>
        <source>SQL query results</source>
        <translation>Resultados de la consulta SQL</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="77"/>
        <location filename="../htmlexport.cpp" line="154"/>
        <source>no type</source>
        <translation>sin tipo</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="114"/>
        <location filename="../htmlexport.cpp" line="242"/>
        <source>Exported table: %1</source>
        <translation>Tabla exportada: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="126"/>
        <location filename="../htmlexport.cpp" line="254"/>
        <source>Table: %1</source>
        <translation>Tabla: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="254"/>
        <source>virtual</source>
        <translation>virtual</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="307"/>
        <source>Exported database: %1</source>
        <translation>Base de datos exportada: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="323"/>
        <source>Index: %1</source>
        <translation>Índice: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="329"/>
        <source>For table:</source>
        <translation>Para la tabla:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="336"/>
        <source>Unique:</source>
        <translation>Único:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="337"/>
        <source>Yes</source>
        <translation>Sí</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="337"/>
        <source>No</source>
        <translation>No</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="343"/>
        <source>Column</source>
        <translation>Columna</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="344"/>
        <source>Collating</source>
        <translation>Cotejamiento</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="345"/>
        <source>Sort order</source>
        <translation>Ordenar por</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="379"/>
        <source>Trigger: %1</source>
        <translation>Disparador: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="385"/>
        <source>Activated:</source>
        <translation>Activado:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="393"/>
        <source>Action:</source>
        <translation>Acción:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="400"/>
        <source>On view:</source>
        <translation>En la vista:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="402"/>
        <source>On table:</source>
        <translation>En la tabla:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="413"/>
        <source>Activate condition:</source>
        <translation>Condición de activación:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="420"/>
        <source>Code executed:</source>
        <translation>Código ejecutado:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="454"/>
        <source>View: %1</source>
        <translation>Vista: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="479"/>
        <source>Document generated by SQLiteStudio v%1 on %2</source>
        <translation>Documento generado por SQLiteStudio v%1 el %2</translation>
    </message>
</context>
<context>
    <name>HtmlExportConfig</name>
    <message>
        <location filename="../htmlexport.ui" line="36"/>
        <source>Maximum number of characters per cell:</source>
        <translation>Número máximo de caracteres por celda:</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="43"/>
        <source>Include data types in first row</source>
        <translation>Incluir tipos de dato en la primera fila</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="53"/>
        <source>Column names as first row</source>
        <translation>Nombres de columna como la primera fila</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="63"/>
        <source>Row numbers as first column</source>
        <translation>Números de fila como la primera columna</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="73"/>
        <source>Output format</source>
        <translation>Formato de salida</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="79"/>
        <source>Format document (new lines, indentation)</source>
        <translation>Formatear documento (nuevas líneas, indentación)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="92"/>
        <source>Compress (everything in one line)</source>
        <translation>Comprimir (todo en una sola línea)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="108"/>
        <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
        <translation>&lt;p&gt;Cuando se activa, caracteres HTML como &amp;lt;, &amp;gt; y &amp; no son escapados en los valores exportados. Esto te permite por ejemplo, exportar documentos con hiper-vínculos funcionales, pero también podría resultar en un documento HTML incorrecto (pares no relacionados de caracteres &amp;lt; y &amp;gt;). Está advertido.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="111"/>
        <source>Don&apos;t escape HTML characters</source>
        <translation>No escapar caracteres HTML</translation>
    </message>
</context>
</TS>
