<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh-CN" sourcelanguage="en">
  <context>
    <name>HtmlExport</name>
    <message>
      <location filename="../htmlexport.cpp" line="45"/>
      <source>SQL query results</source>
      <translation>SQL 查询结果</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="54"/>
      <source>Query:</source>
      <translation>查询：</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="94"/>
      <location filename="../htmlexport.cpp" line="188"/>
      <source>no type</source>
      <translation>无类型</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="125"/>
      <source>Exported table: %1</source>
      <translation>导出的表：%1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="136"/>
      <source>Exported view: %1</source>
      <translation>导出的视图: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="157"/>
      <location filename="../htmlexport.cpp" line="280"/>
      <source>Table: %1</source>
      <translation>表：%1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="283"/>
      <source>virtual</source>
      <translation>虚拟</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="335"/>
      <source>Exported database: %1</source>
      <translation>导出的数据库：%1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="351"/>
      <source>Index: %1</source>
      <translation>索引: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="357"/>
      <source>For table:</source>
      <translation>表：</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="364"/>
      <source>Unique:</source>
      <translation>唯一：</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="365"/>
      <source>Yes</source>
      <translation>是</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="365"/>
      <source>No</source>
      <translation>否</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="371"/>
      <source>Column</source>
      <translation>列</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="372"/>
      <source>Collating</source>
      <translation>字符序</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="373"/>
      <source>Sort order</source>
      <translation>排序方式</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="407"/>
      <source>Trigger: %1</source>
      <translation>触发器：%1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="413"/>
      <source>Activated:</source>
      <translation>激活时间：</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="421"/>
      <source>Action:</source>
      <translation>操作：</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="428"/>
      <source>On view:</source>
      <translation>视图：</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="430"/>
      <source>On table:</source>
      <translation>表：</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="441"/>
      <source>Activate condition:</source>
      <translation>激活条件：</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="448"/>
      <source>Code executed:</source>
      <translation>代码执行：</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="486"/>
      <source>View: %1</source>
      <translation>视图：%1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="565"/>
      <source>Document generated by SQLiteStudio v%1 on %2</source>
      <translation>由 SQLiteStudio v%1 在 %2 生成的文档</translation>
    </message>
  </context>
  <context>
    <name>HtmlExportConfig</name>
    <message>
      <location filename="../htmlexport.ui" line="139"/>
      <source>Maximum number of characters per cell:</source>
      <translation>每个单元格的最大字符数：</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="185"/>
      <source>Include data types in first row</source>
      <translation>第一行包含数据类型</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="146"/>
      <source>Column names as first row</source>
      <translation>列名作为首行</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="129"/>
      <source>Row numbers as first column</source>
      <translation>行号作为首列</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="94"/>
      <source>Output format</source>
      <translation>输出格式</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="20"/>
      <source>Custom header</source>
      <translation>自定义标头</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="26"/>
      <source>No custom header</source>
      <translation>没有自定义标头</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="29"/>
      <location filename="../htmlexport.ui" line="204"/>
      <source>Ctrl+S</source>
      <translation>Ctrl+S</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="42"/>
      <source>Define custom header content</source>
      <translation>定义自定义头部内容</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="55"/>
      <location filename="../htmlexport.ui" line="230"/>
      <source>HTML content</source>
      <translation>HTML 内容</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="65"/>
      <source>Define custom header file</source>
      <translation>定义自定义标头内容</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="81"/>
      <source>Choose file for the header</source>
      <translation>选择文件作为标头</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="84"/>
      <location filename="../htmlexport.ui" line="259"/>
      <source>HTML files (*.htm, *.html);;Text files (*.txt);;All files (*)</source>
      <translation>HTML 文件（*.htm、*.html）；文本文件（*.txt）；所有文件（*）</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="100"/>
      <source>Format document (new lines, indentation)</source>
      <translation>格式化的文档 (新行，缩进)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="113"/>
      <source>Compress (everything in one line)</source>
      <translation>压缩（单行文件）</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="156"/>
      <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
      <translation>&lt;p&gt;如果启用，导出值中不会转义诸如 &amp;lt;、&amp;gt; 和 &amp; 等 HTML 字符。请小心，这使您能导出有超链接的文档，但也可能导致不正确的 HTML 文档（不配对的 &amp;lt; 和 &amp;gt; 字符）。&lt;/p&gt;</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="159"/>
      <source>Don&apos;t escape HTML characters</source>
      <translation>不转义 HTML 字符</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="195"/>
      <source>Custom footer</source>
      <translation>自定义页脚</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="201"/>
      <source>No custom footer</source>
      <translation>没有自定义页脚</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="217"/>
      <source>Define custom footer content</source>
      <translation>定义自定义页脚内容</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="240"/>
      <source>Define custom footer file</source>
      <translation>定义自定义页脚文件</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="256"/>
      <source>Choose file for the footer</source>
      <translation>选择页脚文件</translation>
    </message>
  </context>
</TS>
