<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh-CN" sourcelanguage="en">
  <context>
    <name>HtmlExport</name>
    <message>
      <location filename="../htmlexport.cpp" line="46"/>
      <source>SQL query results</source>
      <translation>SQL 查询结果</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="78"/>
      <location filename="../htmlexport.cpp" line="155"/>
      <source>no type</source>
      <translation type="unfinished">no type</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="115"/>
      <location filename="../htmlexport.cpp" line="243"/>
      <source>Exported table: %1</source>
      <translation type="unfinished">Exported table: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="127"/>
      <location filename="../htmlexport.cpp" line="255"/>
      <source>Table: %1</source>
      <translation>表：%1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="255"/>
      <source>virtual</source>
      <translation type="unfinished">virtual</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="308"/>
      <source>Exported database: %1</source>
      <translation type="unfinished">Exported database: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="324"/>
      <source>Index: %1</source>
      <translation>索引: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="330"/>
      <source>For table:</source>
      <translation type="unfinished">For table:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="337"/>
      <source>Unique:</source>
      <translation type="unfinished">Unique:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="338"/>
      <source>Yes</source>
      <translation>是</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="338"/>
      <source>No</source>
      <translation>否</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="344"/>
      <source>Column</source>
      <translation>字段</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="345"/>
      <source>Collating</source>
      <translation type="unfinished">Collating</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="346"/>
      <source>Sort order</source>
      <translation>排列顺序</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="380"/>
      <source>Trigger: %1</source>
      <translation>触发器：%1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="386"/>
      <source>Activated:</source>
      <translation type="unfinished">Activated:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="394"/>
      <source>Action:</source>
      <translation type="unfinished">Action:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="401"/>
      <source>On view:</source>
      <translation type="unfinished">On view:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="403"/>
      <source>On table:</source>
      <translation type="unfinished">On table:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="414"/>
      <source>Activate condition:</source>
      <translation type="unfinished">Activate condition:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="421"/>
      <source>Code executed:</source>
      <translation type="unfinished">Code executed:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="455"/>
      <source>View: %1</source>
      <translation>视图：%1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="480"/>
      <source>Document generated by SQLiteStudio v%1 on %2</source>
      <translation type="unfinished">Document generated by SQLiteStudio v%1 on %2</translation>
    </message>
  </context>
  <context>
    <name>HtmlExportConfig</name>
    <message>
      <location filename="../htmlexport.ui" line="36"/>
      <source>Maximum number of characters per cell:</source>
      <translation>每个单元的最大字符数：</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="43"/>
      <source>Include data types in first row</source>
      <translation type="unfinished">Include data types in first row</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="53"/>
      <source>Column names as first row</source>
      <translation type="unfinished">Column names as first row</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="63"/>
      <source>Row numbers as first column</source>
      <translation type="unfinished">Row numbers as first column</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="73"/>
      <source>Output format</source>
      <translation>输出格式</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="79"/>
      <source>Format document (new lines, indentation)</source>
      <translation>格式文档 (新行，缩进)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="92"/>
      <source>Compress (everything in one line)</source>
      <translation>压缩（所有数据都将在一行内）</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="108"/>
      <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
      <translation type="unfinished">&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="111"/>
      <source>Don&apos;t escape HTML characters</source>
      <translation type="unfinished">Don&apos;t escape HTML characters</translation>
    </message>
  </context>
</TS>
