<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de" sourcelanguage="en">
  <context>
    <name>HtmlExport</name>
    <message>
      <location filename="../htmlexport.cpp" line="45"/>
      <source>SQL query results</source>
      <translation>SQL Abfragenergebnis</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="77"/>
      <location filename="../htmlexport.cpp" line="171"/>
      <source>no type</source>
      <translation>kein Typ</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="108"/>
      <source>Exported table: %1</source>
      <translation>Exportierte Tabelle: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="119"/>
      <source>Exported view: %1</source>
      <translation type="unfinished">Exported view: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="140"/>
      <location filename="../htmlexport.cpp" line="263"/>
      <source>Table: %1</source>
      <translation>Tabelle: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="266"/>
      <source>virtual</source>
      <translation>virtuell</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="318"/>
      <source>Exported database: %1</source>
      <translation>Exportierte Datenbank: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="334"/>
      <source>Index: %1</source>
      <translation>Index: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="340"/>
      <source>For table:</source>
      <translation>Für Tabelle:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="347"/>
      <source>Unique:</source>
      <translation>Einzigartig:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="348"/>
      <source>Yes</source>
      <translation>Ja</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="348"/>
      <source>No</source>
      <translation>Nein</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="354"/>
      <source>Column</source>
      <translation>Spalte</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="355"/>
      <source>Collating</source>
      <translation>Sortierung</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="356"/>
      <source>Sort order</source>
      <translation>Sortierreihenfolge</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="390"/>
      <source>Trigger: %1</source>
      <translation>Trigger: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="396"/>
      <source>Activated:</source>
      <translation>Aktiviert:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="404"/>
      <source>Action:</source>
      <translation>Aktion:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="411"/>
      <source>On view:</source>
      <translation>Auf Ansicht:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="413"/>
      <source>On table:</source>
      <translation>Auf Tabelle:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="424"/>
      <source>Activate condition:</source>
      <translation>Ausführungsbedingung:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="431"/>
      <source>Code executed:</source>
      <translation>Code ausgeführt:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="469"/>
      <source>View: %1</source>
      <translation>View: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="546"/>
      <source>Document generated by SQLiteStudio v%1 on %2</source>
      <translation>Dokument erstellt von SQLiteStudio v%1 am %2</translation>
    </message>
  </context>
  <context>
    <name>HtmlExportConfig</name>
    <message>
      <location filename="../htmlexport.ui" line="36"/>
      <source>Maximum number of characters per cell:</source>
      <translation>Maximale Zeichenanzahl pro Zelle:</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="43"/>
      <source>Include data types in first row</source>
      <translation>Datentypen in der ersten Zeile einbeziehen</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="53"/>
      <source>Column names as first row</source>
      <translation>Spaltenname als erste Zeile verwenden</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="63"/>
      <source>Row numbers as first column</source>
      <translation>Zeilennummern als erste Spalte</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="73"/>
      <source>Output format</source>
      <translation>Ausgabeformat</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="79"/>
      <source>Format document (new lines, indentation)</source>
      <translation>Dokument formatieren (neue Zeilen, Einrückung)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="92"/>
      <source>Compress (everything in one line)</source>
      <translation>Komprimieren (alles in einer Zeile)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="108"/>
      <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
      <translation>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="111"/>
      <source>Don&apos;t escape HTML characters</source>
      <translation>HTML-Zeichen nicht maskieren</translation>
    </message>
  </context>
</TS>
