<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="pt-BR" sourcelanguage="en">
  <context>
    <name>HtmlExport</name>
    <message>
      <location filename="../htmlexport.cpp" line="46"/>
      <source>SQL query results</source>
      <translation>Resultados da consulta SQL</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="78"/>
      <location filename="../htmlexport.cpp" line="155"/>
      <source>no type</source>
      <translation>sem tipo</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="115"/>
      <location filename="../htmlexport.cpp" line="243"/>
      <source>Exported table: %1</source>
      <translation>Tabela exportada: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="127"/>
      <location filename="../htmlexport.cpp" line="255"/>
      <source>Table: %1</source>
      <translation>Tabela: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="255"/>
      <source>virtual</source>
      <translation>virtual</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="308"/>
      <source>Exported database: %1</source>
      <translation>Banco de dados exportado: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="324"/>
      <source>Index: %1</source>
      <translation>Índice: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="330"/>
      <source>For table:</source>
      <translation>Para a tabela:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="337"/>
      <source>Unique:</source>
      <translation>Único:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="338"/>
      <source>Yes</source>
      <translation>Sim</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="338"/>
      <source>No</source>
      <translation>Não</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="344"/>
      <source>Column</source>
      <translation>Coluna</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="345"/>
      <source>Collating</source>
      <translation>Collating</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="346"/>
      <source>Sort order</source>
      <translation>Ordem de classificação</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="380"/>
      <source>Trigger: %1</source>
      <translation>Trigger: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="386"/>
      <source>Activated:</source>
      <translation>Ativado:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="394"/>
      <source>Action:</source>
      <translation>Ação:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="401"/>
      <source>On view:</source>
      <translation>Na visualização:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="403"/>
      <source>On table:</source>
      <translation>Na tabela:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="414"/>
      <source>Activate condition:</source>
      <translation>Ativar condição:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="421"/>
      <source>Code executed:</source>
      <translation>Código executado:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="455"/>
      <source>View: %1</source>
      <translation>Visualizar: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="480"/>
      <source>Document generated by SQLiteStudio v%1 on %2</source>
      <translation>Documento gerado por SQLiteStudio v%1 em %2</translation>
    </message>
  </context>
  <context>
    <name>HtmlExportConfig</name>
    <message>
      <location filename="../htmlexport.ui" line="36"/>
      <source>Maximum number of characters per cell:</source>
      <translation>Número máximo de caracteres por célula:</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="43"/>
      <source>Include data types in first row</source>
      <translation>Incluir tipos de dados na primeira linha</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="53"/>
      <source>Column names as first row</source>
      <translation>Nomes de coluna como primeira linha</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="63"/>
      <source>Row numbers as first column</source>
      <translation>Linha de números como a primeira coluna</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="73"/>
      <source>Output format</source>
      <translation>Formato de saída</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="79"/>
      <source>Format document (new lines, indentation)</source>
      <translation>Formatar documento (novas linhas, recuo)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="92"/>
      <source>Compress (everything in one line)</source>
      <translation>Comprimir (tudo em uma linha)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="108"/>
      <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
      <translation>&lt;p&gt;Quando habilitado, caracteres HTML como &amp;lt;, &amp;gt; e &amp; não são escapados nos valores exportados. Isso permite a você, por exemplo, exportar documentos habilitados de hiper-links, mas também pode resultar em documentos HTML incorretos (pares não correspondentes de &amp;lt; e &amp;gt; caracteres). Estejam avisados.&lt;/p&gt;</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="111"/>
      <source>Don&apos;t escape HTML characters</source>
      <translation>Não é possível caracteres HTML</translation>
    </message>
  </context>
</TS>
