<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="he" sourcelanguage="en">
<context>
    <name>HtmlExport</name>
    <message>
        <location filename="../htmlexport.cpp" line="45"/>
        <source>SQL query results</source>
        <translation>תוצאות שאילתת SQL</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="54"/>
        <source>Query:</source>
        <translation type="unfinished">Query:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="94"/>
        <location filename="../htmlexport.cpp" line="188"/>
        <source>no type</source>
        <translation>ללא סוג</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="125"/>
        <source>Exported table: %1</source>
        <translation>טבלה מיוצת: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="136"/>
        <source>Exported view: %1</source>
        <translation type="unfinished">Exported view: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="157"/>
        <location filename="../htmlexport.cpp" line="280"/>
        <source>Table: %1</source>
        <translation>טבלה: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="283"/>
        <source>virtual</source>
        <translation>מְדֻמֶּה</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="335"/>
        <source>Exported database: %1</source>
        <translation>מסד נתונים מיוצא: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="351"/>
        <source>Index: %1</source>
        <translation>מִפְתֵּחַ: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="357"/>
        <source>For table:</source>
        <translation>עבור טבלה:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="364"/>
        <source>Unique:</source>
        <translation>ייחודי:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>Yes</source>
        <translation>כן</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>No</source>
        <translation>לא</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="371"/>
        <source>Column</source>
        <translation>עמודה</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="372"/>
        <source>Collating</source>
        <translation>ארגון</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="373"/>
        <source>Sort order</source>
        <translation>סדר מיון</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="407"/>
        <source>Trigger: %1</source>
        <translation>מַזְנֵק: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="413"/>
        <source>Activated:</source>
        <translation>מופעל:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="421"/>
        <source>Action:</source>
        <translation>פעולה:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="428"/>
        <source>On view:</source>
        <translation>אין מצג:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="430"/>
        <source>On table:</source>
        <translation>אין טבלה:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="441"/>
        <source>Activate condition:</source>
        <translation>שפעול תנאי:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="448"/>
        <source>Code executed:</source>
        <translation>קוד בוצע:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="486"/>
        <source>View: %1</source>
        <translation>מצג: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="565"/>
        <source>Document generated by SQLiteStudio v%1 on %2</source>
        <translation>מסמך חולל על ידי SQLiteStudio v%1 ב %2</translation>
    </message>
</context>
<context>
    <name>HtmlExportConfig</name>
    <message>
        <location filename="../htmlexport.ui" line="139"/>
        <source>Maximum number of characters per cell:</source>
        <translation>מספר תווים מזערי בכל תא:</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="185"/>
        <source>Include data types in first row</source>
        <translation>הכללת סוגי נתונים בשורה ראשונה</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="146"/>
        <source>Column names as first row</source>
        <translation>שמות עמודות בשורה ראשונה</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="129"/>
        <source>Row numbers as first column</source>
        <translation>מספר שורה כעמודה ראשונה</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="94"/>
        <source>Output format</source>
        <translation>תבנית פלט</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="20"/>
        <source>Custom header</source>
        <translation type="unfinished">Custom header</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="26"/>
        <source>No custom header</source>
        <translation type="unfinished">No custom header</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="29"/>
        <location filename="../htmlexport.ui" line="204"/>
        <source>Ctrl+S</source>
        <translation type="unfinished">Ctrl+S</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="42"/>
        <source>Define custom header content</source>
        <translation type="unfinished">Define custom header content</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="55"/>
        <location filename="../htmlexport.ui" line="230"/>
        <source>HTML content</source>
        <translation type="unfinished">HTML content</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="65"/>
        <source>Define custom header file</source>
        <translation type="unfinished">Define custom header file</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="81"/>
        <source>Choose file for the header</source>
        <translation type="unfinished">Choose file for the header</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="84"/>
        <location filename="../htmlexport.ui" line="259"/>
        <source>HTML files (*.htm, *.html);;Text files (*.txt);;All files (*)</source>
        <translation type="unfinished">HTML files (*.htm, *.html);;Text files (*.txt);;All files (*)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="100"/>
        <source>Format document (new lines, indentation)</source>
        <translation>תבנות מסמך (שורה חדשה, הזחה)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="113"/>
        <source>Compress (everything in one line)</source>
        <translation>דחיסה (הכל בשורה אחת)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="156"/>
        <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
        <translation>&lt;p&gt;אם אופשר, תווי HTML כגון &amp;lt;, &amp;gt; ו-&amp; לא יחמקו ויכללו בערכים שיוצאו.כלומר, זה יאפשר לייצא מסמכים המופעלים באמצעות קישור, אך עלול להסתיים במסמך HTML פגום (זוגות תווים &amp;lt; and &amp;gt; לא תואמים). לתשומת לב. &lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="159"/>
        <source>Don&apos;t escape HTML characters</source>
        <translation>לא לחמוק מתווי HTML</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="195"/>
        <source>Custom footer</source>
        <translation type="unfinished">Custom footer</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="201"/>
        <source>No custom footer</source>
        <translation type="unfinished">No custom footer</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="217"/>
        <source>Define custom footer content</source>
        <translation type="unfinished">Define custom footer content</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="240"/>
        <source>Define custom footer file</source>
        <translation type="unfinished">Define custom footer file</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="256"/>
        <source>Choose file for the footer</source>
        <translation type="unfinished">Choose file for the footer</translation>
    </message>
</context>
</TS>
